name:                graphcoloring
version:             0.1.0.0
github:              "mmsbrggr/graphcoloring"
license:             BSD3
author:              "Marcel Moosbrugger"
copyright:           "2018 Marcel Moosbrugger"

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/mmsbrggr/graphcoloring#readme>

dependencies:
- base >= 4.7 && < 5
- text
- matrix
- vector
- parsec
- QuickCheck
- hspec

library:
  source-dirs: src

executables:
  graphcoloring-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphcoloring

tests:
  graphcoloring-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependecies:
    - graphcoloring
